easy_admin:
  entities:
    Currency:
      class: App\Entity\Currency
      edit:
        fields:
          - { property: 'name', type_options: { disabled: true } }
          - { property: 'symbol', type_options: { disabled: true } }
          - { property: 'uniqueName', type_options: { disabled: true } }
          - { property: 'rank', type_options: { disabled: true } }
          - history
      list:
        sort: ['rank', 'ASC']
    Contact:
      class: App\Entity\Contact
      list:
        sort: ['createdAt', 'ASC']
    Article:
      class: App\Entity\Article
      list:
        sort: ['id', 'ASC']
    User:
      class: App\Entity\User
      list:
        sort: ['id', 'ASC']
    TradingWallet:
      class: App\Entity\TradingWallet
      list:
        sort: ['id', 'ASC']
    Logs:
      class: App\Entity\UpdatePriceLogs
      list:
        sort: ['id', 'DESC']