<?php

namespace AppBundle\Repository;

/**
 * EuroWalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EuroWalletRepository extends \Doctrine\ORM\EntityRepository
{
}
