<?php

namespace AppBundle\Repository;

/**
 * MyCryptoWalletDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyCryptoWalletDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
