<?php

namespace AppBundle\Repository;

/**
 * OrderMethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderMethodRepository extends \Doctrine\ORM\EntityRepository
{
}
