<?php

namespace AppBundle\Repository;

/**
 * OrderActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderActionRepository extends \Doctrine\ORM\EntityRepository
{
}
