<?php

namespace AppBundle\Repository;

/**
 * TradingOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradingOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
