<?php

namespace App\Repository;

/**
 * CurrencyWalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyWalletRepository extends \Doctrine\ORM\EntityRepository
{
}
