<?php

namespace App\Repository;

/**
 * CurrencyValueHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyValueHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
