<?php

namespace App\Repository;

/**
 * CurrencyValueMomentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyValueMomentRepository extends \Doctrine\ORM\EntityRepository
{
}
