<?php

namespace App\Repository;

/**
 * TradingWalletRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradingWalletRepository extends \Doctrine\ORM\EntityRepository
{
}
